/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Traceback (most recent call last):
  File "/home/jahan/Missingness/train.py", line 143, in <module>
    metrics_df, perc_missing = run(
  File "/home/jahan/Missingness/benchmarkaux/openmlrun.py", line 229, in run
    wandb.log({"gbm_nll_fold{}".format(count):nll}, commit=False)
UnboundLocalError: local variable 'nll' referenced before assignment
name: Supervised Classification, features: dresses-sales
{'X_train': {'cols': 0.13505747126436782, 'rows': 0.7787356321839081}, 'X_valid': {'cols': 0.14393939393939395, 'rows': 0.8522727272727273}, 'X_test': {'cols': 0.14733333333333334, 'rows': 0.8}}
dataset sizes
(358, 12) (88, 12) (125, 12)
dropped dataset sizes
(79, 12) (13, 12) (25, 12)
key: 5092, k: 1/4, dataset: 23381, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 11, 'max_bin': 106, 'max_depth': 13, 'min_data_in_leaf': 10, 'learning_rate': 0.8835678894382731, 'num_iterations': 503, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[3]	valid_0's multi_logloss: 0.603156
strategy:None, acc gbm: 0.568