name: Supervised Regression, features: SAT11-HAND-runtime-regression
{'X_train': {'cols': 0.053102671637154396, 'rows': 0.615990990990991}, 'X_valid': {'cols': 0.05061095578336958, 'rows': 0.5870870870870871}, 'X_test': {'cols': 0.05304442373407891, 'rows': 0.6153153153153154}}
dataset sizes
(2664, 116) (666, 116) (1110, 116)
dropped dataset sizes
(1023, 116) (275, 116) (427, 116)
key: 1648, k: 1/4, dataset: 41980, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 21, 'max_bin': 236, 'max_depth': 18, 'min_data_in_leaf': 11, 'learning_rate': 0.7501586540718519, 'num_iterations': 696, 'objective': 'regression', 'verbose': -1, 'num_class': 1}
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[33]	valid_0's l2: 0.283019
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/basic.py:179: UserWarning: Converting column-vector to 1d array
  _log_warning('Converting column-vector to 1d array')
Traceback (most recent call last):
  File "/home/jahan/Missingness/train.py", line 143, in <module>
    metrics_df, perc_missing = run(
  File "/home/jahan/Missingness/benchmarkaux/openmlrun.py", line 225, in run
    wandb.log({"gbm_rmse_fold{}".format(count):rmse}, commit=False)
UnboundLocalError: local variable 'rmse' referenced before assignment