name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.016692498173979657, 'rows': 0.4869684499314129}, 'X_valid': {'cols': 0.012632176566602796, 'rows': 0.40437158469945356}, 'X_test': {'cols': 0.018518518518518517, 'rows': 0.5222222222222223}}
dataset sizes
(776, 77) (183, 77) (270, 77)
dropped dataset sizes
(401, 77) (109, 77) (129, 77)
key: 6519, k: 1/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 38, 'max_bin': 119, 'max_depth': 22, 'min_data_in_leaf': 15, 'learning_rate': 3.706616846076993e-05, 'num_iterations': 683, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[683]	valid_0's multi_logloss: 1.97259
strategy:None, acc gbm: 0.8074074074074075
strategy:None, nll xbg:2.014854907989502
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.018529357965977687, 'rows': 0.4915492957746479}, 'X_valid': {'cols': 0.015759521377498902, 'rows': 0.43820224719101125}, 'X_test': {'cols': 0.014718614718614718, 'rows': 0.48148148148148145}}
dataset sizes
(744, 77) (178, 77) (270, 77)
dropped dataset sizes
(377, 77) (100, 77) (140, 77)
key: 4105, k: 2/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 38, 'max_bin': 119, 'max_depth': 22, 'min_data_in_leaf': 15, 'learning_rate': 3.706616846076993e-05, 'num_iterations': 683, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[683]	valid_0's multi_logloss: 1.98162
strategy:None, acc gbm: 0.737037037037037
strategy:None, nll xbg:2.0114238262176514
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.015906574046108932, 'rows': 0.4689922480620155}, 'X_valid': {'cols': 0.01566474762351051, 'rows': 0.5}, 'X_test': {'cols': 0.017075517075517074, 'rows': 0.4703703703703704}}
dataset sizes
(816, 77) (194, 77) (270, 77)
dropped dataset sizes
(430, 77) (97, 77) (143, 77)
key: 2254, k: 3/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 38, 'max_bin': 119, 'max_depth': 22, 'min_data_in_leaf': 15, 'learning_rate': 3.706616846076993e-05, 'num_iterations': 683, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[683]	valid_0's multi_logloss: 1.9678
strategy:None, acc gbm: 0.8
strategy:None, nll xbg:2.0127549171447754
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.015245623941276116, 'rows': 0.4796195652173913}, 'X_valid': {'cols': 0.019339356295878036, 'rows': 0.483695652173913}, 'X_test': {'cols': 0.01683501683501683, 'rows': 0.48148148148148145}}
dataset sizes
(784, 77) (184, 77) (270, 77)
dropped dataset sizes
(414, 77) (95, 77) (140, 77)
key: 198, k: 4/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 38, 'max_bin': 119, 'max_depth': 22, 'min_data_in_leaf': 15, 'learning_rate': 3.706616846076993e-05, 'num_iterations': 683, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[683]	valid_0's multi_logloss: 1.97554
strategy:None, acc gbm: 0.774074074074074
strategy:None, nll xbg:2.0107052326202393