name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.01622931252560882, 'rows': 0.4787379972565158}, 'X_valid': {'cols': 0.014903129657228018, 'rows': 0.45901639344262296}, 'X_test': {'cols': 0.018518518518518517, 'rows': 0.5222222222222223}}
dataset sizes
(752, 77) (183, 77) (270, 77)
dropped dataset sizes
(391, 77) (99, 77) (129, 77)
key: 7158, k: 1/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 10, 'max_bin': 75, 'max_depth': 9, 'min_data_in_leaf': 17, 'learning_rate': 0.00422167759318371, 'num_iterations': 585, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[585]	valid_0's multi_logloss: 0.198759
strategy:None, acc gbm: 0.9444444444444444
strategy:None, nll xbg:0.26649603247642517
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.016517285531370038, 'rows': 0.48450704225352115}, 'X_valid': {'cols': 0.017364657814096015, 'rows': 0.4550561797752809}, 'X_test': {'cols': 0.014718614718614718, 'rows': 0.48148148148148145}}
dataset sizes
(760, 77) (178, 77) (270, 77)
dropped dataset sizes
(396, 77) (97, 77) (140, 77)
key: 8141, k: 2/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 10, 'max_bin': 75, 'max_depth': 9, 'min_data_in_leaf': 17, 'learning_rate': 0.00422167759318371, 'num_iterations': 585, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[585]	valid_0's multi_logloss: 0.235751
strategy:None, acc gbm: 0.9481481481481482
strategy:None, nll xbg:0.27006134390830994
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.016091143998120745, 'rows': 0.4702842377260982}, 'X_valid': {'cols': 0.01526308742803588, 'rows': 0.4793814432989691}, 'X_test': {'cols': 0.017075517075517074, 'rows': 0.4703703703703704}}
dataset sizes
(816, 77) (194, 77) (270, 77)
dropped dataset sizes
(429, 77) (101, 77) (143, 77)
key: 4547, k: 3/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 10, 'max_bin': 75, 'max_depth': 9, 'min_data_in_leaf': 17, 'learning_rate': 0.00422167759318371, 'num_iterations': 585, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[585]	valid_0's multi_logloss: 0.216255
strategy:None, acc gbm: 0.9740740740740741
strategy:None, nll xbg:0.18491315841674805
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.01476919819311124, 'rows': 0.47146739130434784}, 'X_valid': {'cols': 0.020680406549971768, 'rows': 0.4891304347826087}, 'X_test': {'cols': 0.01683501683501683, 'rows': 0.48148148148148145}}
dataset sizes
(768, 77) (184, 77) (270, 77)
dropped dataset sizes
(409, 77) (94, 77) (140, 77)
key: 1632, k: 4/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 10, 'max_bin': 75, 'max_depth': 9, 'min_data_in_leaf': 17, 'learning_rate': 0.00422167759318371, 'num_iterations': 585, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[585]	valid_0's multi_logloss: 0.194155
strategy:None, acc gbm: 0.9629629629629629
strategy:None, nll xbg:0.2470223307609558