name: Supervised Classification, features: sick
{'X_train': {'cols': 0.0136955205811138, 'rows': 0.2059792843691149}, 'X_valid': {'cols': 0.013283562012375572, 'rows': 0.19303201506591336}, 'X_test': {'cols': 0.02109528859263748, 'rows': 0.28207847295864263}}
dataset sizes
(4256, 28) (1062, 28) (943, 28)
dropped dataset sizes
(3375, 28) (857, 28) (677, 28)
key: 8240, k: 1/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 39, 'max_bin': 188, 'max_depth': 5, 'min_data_in_leaf': 30, 'learning_rate': 0.06535812568994866, 'num_iterations': 567, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[155]	valid_0's multi_logloss: 0.0310404
strategy:None, acc gbm: 0.9840933191940615
strategy:None, nll xbg:0.08457013219594955
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.014841755140438114, 'rows': 0.21025399811853246}, 'X_valid': {'cols': 0.010707572502685284, 'rows': 0.16635338345864661}, 'X_test': {'cols': 0.020565065899106196, 'rows': 0.29056203605514314}}
dataset sizes
(4284, 28) (1064, 28) (943, 28)
dropped dataset sizes
(3387, 28) (887, 28) (669, 28)
key: 3832, k: 2/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 39, 'max_bin': 188, 'max_depth': 5, 'min_data_in_leaf': 30, 'learning_rate': 0.06535812568994866, 'num_iterations': 567, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Early stopping, best iteration is:
[351]	valid_0's multi_logloss: 0.00129717
strategy:None, acc gbm: 0.9915164369034994
strategy:None, nll xbg:0.09730938822031021
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.012768276324614353, 'rows': 0.18544600938967137}, 'X_valid': {'cols': 0.012798177432323777, 'rows': 0.1801125703564728}, 'X_test': {'cols': 0.02238297227692774, 'rows': 0.3149522799575822}}
dataset sizes
(4272, 28) (1066, 28) (943, 28)
dropped dataset sizes
(3481, 28) (874, 28) (646, 28)
key: 8292, k: 3/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 39, 'max_bin': 188, 'max_depth': 5, 'min_data_in_leaf': 30, 'learning_rate': 0.06535812568994866, 'num_iterations': 567, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[538]	valid_0's multi_logloss: 0.0133015
strategy:None, acc gbm: 0.9883351007423118
strategy:None, nll xbg:0.16253724694252014
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013282172373081463, 'rows': 0.19551357733175914}, 'X_valid': {'cols': 0.01389450964521786, 'rows': 0.20113314447592068}, 'X_test': {'cols': 0.022761702772307223, 'rows': 0.30965005302226933}}
dataset sizes
(4258, 28) (1059, 28) (943, 28)
dropped dataset sizes
(3429, 28) (846, 28) (651, 28)
key: 3687, k: 4/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 39, 'max_bin': 188, 'max_depth': 5, 'min_data_in_leaf': 30, 'learning_rate': 0.06535812568994866, 'num_iterations': 567, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Early stopping, best iteration is:
[291]	valid_0's multi_logloss: 0.00742818
strategy:None, acc gbm: 0.9915164369034994
strategy:None, nll xbg:0.044529322534799576